[variables]
CADDY_VERSION = '2.7.6'

[phases.caddy]
dependsOn = ['setup']
cmds = [
    'curl -fsSLo caddy.tar.gz "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_amd64.tar.gz"',
    'tar -zxvf caddy.tar.gz caddy',
    'chmod +x caddy'
]

[start]
cmd = './caddy run --config Caddyfile --adapter caddyfile 2>&1'
